import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    'projects/intro',
    'projects/frontend/intro',
    'projects/backend/intro',
    'projects/infrastructure/intro',
    'projects/powershell/intro',
    'projects/contributions',
  ],
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  booksSidebar: [
    {
      type: 'autogenerated',
      dirName: 'books',
    },
  ],
};

export default sidebars;
