# Pre-build configuration settings
preBuild:
  # Project root directory, relative to the main docs directory
  projectRoot: ../
  overwriteExistingFiles: true
  copyMarkdownFromProjectRoot: false
  generateNavBarForPages: true
  defaultTheme: blue

site:
  title: Portfolio
  tagline: Technical Projects & Experience
  url: https://portfolio.subzerodev.com
  baseUrl: /
  organizationName: The-Running-Dev
  projectName: Portfolio

theme:
  navbar:
    title: Portfolio
    logo:
      alt: Portfolio
      src: img/logo.svg

features:
  giscusComments: false
  gitHubLinks: true
  navBarLinks: true
  badges: true
  themeSwitcher: false
  textSizeSwitcher: true
  readerMode: true
  versionDisplay: true
  cvPage: true
  portfolioPage: true
  portfolioPageAsIndex: true
  projectsPage: true
  dataCaching: true

# projects:
#   provider: http
#   location: http://localhost:3001/api/v1/projects

# projects:
#   provider: json # JSON file provider, or 'http' for API
#   location: ./data/projects.json # or URL: 'https://api.subzerodev.com/projects'