name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/the-running-dev/build-agent:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark as Safe for Git
        run: git config --global --add safe.directory /__w/Portfolio/Portfolio

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Build and Deploy
        run: pwsh ./build-and-deploy.ps1
        env:
          GIT_USER: The-Running-Dev
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}